package com.cgm.registrootmongodb.enumeration;

public enum Estado {
    EN_CONFIGURACION,
    SOLICITUD_FUENTES,
    A_PRODUCCION,
    SOLICITUD_FOLIO,
    EN_PRODUCCION,
    A_CONGIGURACION,
    APROBACION_USUARIO,
    EN_APROBACION_USUARIO,
    REGULARIZACION
}
